name: Coverage Testing

on: [workflow_dispatch, push, pull_request]

permissions: read-all

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ 22, 24 ]
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
    name: Ubuntu - Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install Application
        run: |
          npm ci
          npm install -g c8 cypress@15

      - name: Copy Test Config
        run: cp ./data/testing.config.js ./data/config.js
        
      - name: Test Application Startup
        run: npm run test:startup

      - name: Verify Cypress
        run: cypress verify
        env:
          CYPRESS_VERIFY_TIMEOUT: 600000

      - name: Run Coverage Testing
        run: npm run coverage

      - name: Codecov
        if: ${{ github.event_name != 'pull_request' && env.CODECOV_TOKEN != '' && matrix.node == 22 }}
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}

  Windows:
    runs-on: windows-2025
    strategy:
      fail-fast: false
      matrix:
        node: [ 20, 22 ]

    name: Windows - Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v5
      
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install Application
        run: |
          npm ci
          npm install -g cypress@15

      - name: Copy Test Config
        run: cp ./data/testing.config.js ./data/config.js
        
      - name: Run Test
        run: node --test --test-concurrency 1

  Mac:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ 22, 24 ]

    name: MacOS - Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v5
      
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install Application
        run: |
          npm ci
          npm install -g cypress@15

      - name: Copy Test Config
        run: cp ./data/testing.config.js ./data/config.js
        
      - name: Run Test
        run: node --test --test-concurrency 1
